services:
  momentum:
    build: .
    ports: ["8000:8000"]
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - ALPACA_FEED=${ALPACA_FEED:-iex}
    volumes:
      - ./tickers.csv:/app/tickers.csv:ro
